jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-interaction

      # ✅ Add this step to copy .env.example and generate APP_KEY
      - name: Set up Laravel environment
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan config:clear

      - name: Run Laravel tests
        run: php artisan test
