name: Laravel Deployer

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter the branch name to deploy'
        required: true
        default: 'main'
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, intl
          coverage: none
      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --no-interaction
        
      - name: Run Laravel tests
        run: php artisan test

      - name: Run Laravel tests
        run: php artisan optimize

  deploy:
    runs-on: ubuntu-latest
    needs: test   # ✅ Only deploy if tests pass
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Deploy to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ""
          username: ""
          password: ""
          port: "21"
          local-dir: ./
